name: Run
on:
  push:
  pull_request:

jobs:
  c:
    name: Run C
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install required tools
        run: sudo apt-get install --no-install-recommends clang llvm qemu-system-riscv64
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Run
        working-directory: c
        run: bash run.sh

  rust:
    name: Run Rust
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install required tools
        run: sudo apt-get install --no-install-recommends qemu-system-riscv64
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          target: riscv64gc-unknown-none-elf

      - name: Run
        working-directory: rust
        run: bash run.sh
